# -*- coding: utf-8 -*-
"""CustomYOLOv12_Doc_Lysa_[Student_Version].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14p1k6NSGhQQA5_B7XWaXPzDBBQ2r9BkX

## ⚠️ Notice

## This material is the intellectual property of <font color="cyan">Dr. Lysa V. Comia.</font>

Redistribution, reproduction, or use beyond personal reference is strictly prohibited without the prior written consent of the author.

## Connect Google Drive
"""

from google.colab import drive

# Mount Google Drive to access datasets, pretrained models, and save training outputs.
# When prompted, follow the authorization link and paste the access code below.

drive.mount('/content/drive')

"""## Installation"""

# Commented out IPython magic to ensure Python compatibility.
# Navigate to the project directory in Google Drive
# Ensure this path matches the location of your YOLOv12 project files.

# %cd /content/drive/MyDrive/Proj_YOLOv12

# Clone the YOLOv12 repository
# (Uncomment this code below if cloning for the first time,
# then comment it out again after the initial setup to avoid recloning.)

!git clone https://github.com/sunsmarterjie/yolov12.git

# Commented out IPython magic to ensure Python compatibility.
# Move into the YOLOv12 repository directory
# This assumes you have already cloned or copied the yolov12 folder inside your project path.

# %cd yolov12

# Commented out IPython magic to ensure Python compatibility.
# # Install project dependencies
# # We overwrite requirements.txt with fixed versions to ensure compatibility in Colab.
# # This prevents mismatched or outdated package versions during installation.
# 
# %%writefile requirements.txt
# torch==2.2.2
# torchvision==0.17.2
# timm==1.0.14
# albumentations==2.0.4
# pycocotools==2.0.7
# PyYAML==6.0.1
# scipy==1.13.0
# onnxslim==0.1.31
# onnxruntime-gpu==1.18.0
# gradio==4.44.1
# opencv-python==4.9.0.80
# psutil==5.9.8
# py-cpuinfo==9.0.0
# huggingface-hub==0.23.2
# safetensors==0.4.3
# numpy==1.26.4
# supervision==0.22.0

!pip install -r requirements.txt

# Upgrade core packaging tools to the latest versions
# Ensures smooth installation of dependencies and prevents build errors.
!pip install -U pip setuptools wheel

# Install ONNX with prebuilt binaries only (no source build)
# This avoids compilation errors in Colab by forcing a wheel install.
!pip install --only-binary=:all: "onnx==1.16.2"

# Commented out IPython magic to ensure Python compatibility.
# Change directory to the YOLOv12 repository inside your project folder
# Make sure the yolov12 folder exists in this path before running.
# %cd /content/drive/MyDrive/Proj_YOLOv12/yolov12

# Reinstall FlashAttention to ensure compatibility with Colab environment
# Step 1: Uninstall any conflicting versions
!pip uninstall -y flash-attn flash_attn

# Step 2: Force reinstall the correct version (2.6.3) without using cache
!pip install --no-cache-dir --force-reinstall "flash-attn==2.6.3"

# Commented out IPython magic to ensure Python compatibility.
# Navigate back into the YOLOv12 project directory
# This ensures subsequent training or evaluation commands run inside the repo.
# %cd /content/drive/MyDrive/Proj_YOLOv12/yolov12

# Install YOLOv12 in editable/development mode
# This allows you to modify the repository code and immediately use the changes without reinstalling.
!pip install -e .

# Commented out IPython magic to ensure Python compatibility.
# Ensure we are inside the YOLOv12 repository directory
# This is important before running training, validation, or inference scripts.
# %cd /content/drive/MyDrive/Proj_YOLOv12/yolov12

# Install the specific Ultralytics version required for YOLOv12
# -U flag upgrades if an older version is already installed
!pip install -U ultralytics==8.3.176

# Download YOLOv12/YOLOv11 pretrained weights
# ⚠️ IMPORTANT: Uncomment ONLY the line you need, then comment it again after the first run
# to avoid downloading the file repeatedly in Colab.

# 📖 Full documentation and complete list of YOLOv12 model variants:
# https://docs.ultralytics.com/models/yolo12/

# --- For Object Detection ---
# !wget https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo12n.pt

# --- For Object Segmentation ---
!wget https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-seg.pt

"""## Training"""

from ultralytics import YOLO

# Initialize the YOLO model
# ⚠️ Use the appropriate checkpoint:
# - yolo12n.pt       → for object detection
# - yolo11n-seg.pt   → for object segmentation
model = YOLO('/content/drive/MyDrive/Proj_YOLOv12/yolov12/yolo11n-seg.pt')

# Train the model
results = model.train(
    data='/content/drive/MyDrive/Proj_YOLOv12/braintumor_yolov12v5/data.yaml',  # dataset config file
    epochs=1000,       # maximum epochs (early stopping may end sooner)
    patience=15,       # stop if no improvement for 15 epochs
    batch=8,           # batch size
    imgsz=640,         # input image size
    scale=0.5,         # data augmentation scaling
    mosaic=1.0,        # mosaic augmentation probability
    mixup=0.0,         # mixup probability
    copy_paste=0.1,    # copy-paste augmentation probability
    close_mosaic=10,   # disable mosaic augmentation in the last 10 epochs
    device="0",        # set to "0" for GPU, "cpu" for CPU
    save=True          # save both best.pt and last.pt
)

"""## Testing"""

from ultralytics import YOLO
import cv2
from matplotlib import pyplot as plt
import numpy as np

# Load trained YOLOv12 segmentation model weights
model = YOLO("/content/drive/MyDrive/Proj_YOLOv12/yolov12/runs/segment/train4/weights/best.pt")

# Test image path
img_path = "/content/drive/MyDrive/Proj_YOLOv12/braintumor_yolov12v5/test/images/enh_Tr-pi_1450_jpg.rf.99a73245080d1e77b9be78f97d32885c.jpg"

# Run inference
results = model(img_path)

# Process and visualize results
for r in results:
    # Load the original image (full resolution)
    img = cv2.imread(img_path)

    # Overlay segmentation masks
    if r.masks is not None:
        masks = r.masks.data.cpu().numpy()
        for mask in masks:
            mask = mask.astype(np.uint8) * 255
            colored_mask = np.zeros_like(img)
            colored_mask[:, :, 2] = mask  # Red overlay for segmentation
            img = cv2.addWeighted(img, 1.0, colored_mask, 0.5, 0)

    # Draw bounding boxes, labels, and confidence scores
    boxes = r.boxes.xyxy.cpu().numpy()
    scores = r.boxes.conf.cpu().numpy()       # confidence scores
    class_ids = r.boxes.cls.cpu().numpy().astype(int)  # class IDs
    names = model.names                       # class name mapping

    for box, score, cls_id in zip(boxes, scores, class_ids):
        x1, y1, x2, y2 = map(int, box)
        label = f"{names[cls_id]} {score:.2f}"  # e.g. "tilapia 0.93"

        # Draw rectangle
        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)

        # Put label + score above the box
        cv2.putText(img, label, (x1, max(y1 - 10, 0)),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2,
                    lineType=cv2.LINE_AA)

    # Display image at original resolution
    h, w = img.shape[:2]
    dpi = 300
    fig_w, fig_h = w / dpi, h / dpi
    fig, ax = plt.subplots(figsize=(fig_w, fig_h), dpi=dpi)

    ax.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB), interpolation='nearest')
    ax.axis("off")
    plt.show()

"""## Logs"""

# --------------------------------------------------------------
# Save and Collect Training Logs
# These logs will later be used for data visualization
# (e.g., loss curves, mAP, precision/recall) in documentation or papers.
# --------------------------------------------------------------

import shutil

# Define source (YOLO training logs) and destination (your Drive folder for papers)
src = "/content/drive/MyDrive/Proj_YOLOv12/yolov12/runs"
dst = "/content/drive/MyDrive/Proj_YOLOv12/logs_for_visualization"

# Copy all run logs (metrics, results.csv, tensorboard files, etc.)
shutil.copytree(src, dst, dirs_exist_ok=True)

print(f"✅ Logs copied to: {dst}")

"""# Custom YOLOv12 Brain Tumor Detection – Full Documentation

## **Abstract**
This project implements a custom object detection model using **YOLOv12** to detect and classify brain tumors into **Glioma**, **Meningioma**, and **Pituitary** categories from MRI scans. The notebook integrates data preprocessing, training, and inference within the Google Colab environment. This documentation outlines the workflow, methods, and findings, serving both as a technical reference and a formal research-style report.

---

## **1. Technical Documentation**

### **1.1 Environment Setup**
The notebook begins by mounting Google Drive to access datasets, pretrained models, and to save output files. This ensures that large datasets and training logs are stored persistently across Colab sessions.

from google.colab import drive

drive.mount('/content/drive')

---

### **1.2 Installation and Repository Setup**
The YOLOv12 repository is cloned from GitHub and installed in editable mode. This installs all dependencies required for YOLOv12, including PyTorch and Ultralytics modules.

%cd /content/drive/MyDrive/Proj_YOLOv12

!git clone https://github.com/sunsmarterjie/yolov12.git

---

### **1.3 Dataset Configuration**
A configuration file (data.yaml) defines dataset paths, class names, and data splits (train, validation, test). The dataset consists of MRI images labeled with three tumor categories: Glioma, Meningioma, and Pituitary.

---

### **1.4 Model Initialization**
The YOLOv12 model is loaded using Ultralytics’ API. It supports both segmentation and detection tasks. Users can select pre-trained checkpoints like yolo12n.pt or yolo11n-seg.pt.

from ultralytics import YOLO
model = YOLO('yolo12n.pt')

---

### **1.5 Model Training**
Training is performed with a defined set of hyperparameters controlling image size, batch size, learning rate, augmentation, and early stopping. The notebook logs losses, precision, recall, and mAP during training.

model.train(data='data.yaml', epochs=1000, batch=8, imgsz=640, patience=15, device='0')

Key hyperparameters:
epochs = 1000
batch = 8
imgsz = 640
mosaic = 1.0
copy_paste = 0.1
patience = 15

---

### **1.6 Inference and Visualization**
After training, the best model weights are saved as best.pt. Inference is run on MRI test images, and results are visualized with bounding boxes and confidence scores using OpenCV and Matplotlib.

results = model('/content/test_image.jpg')
results.show()

---

### **1.7 Output and Logging**
Training logs, model weights, and plots are automatically saved under /runs/train. These include:
- results.csv – training metrics
- TensorBoard logs
- Example detections

---

## **2. Research-Style Methodology and Discussion**

### **2.1 Methodology**

Dataset Preprocessing:
Images are resized to 640×640, normalized, and augmented using YOLO’s native techniques (mosaic, mixup, copy-paste).

Model Configuration:
YOLOv12 uses an attention-optimized backbone and transformer-based neck for better feature fusion. Training applies multi-loss optimization combining box, class, segmentation, and distribution focal losses.

Training Environment:
Training and validation were performed on Google Colab GPUs with CUDA acceleration. The optimizer (SGD / AdamW) used dynamic learning-rate scheduling and early stopping after 15 stagnant epochs.

Evaluation Strategy:
Model performance was evaluated using mAP@0.5, mAP@0.5–0.95, precision, and recall on the validation set.

---

### **2.2 Results and Discussion**

Detection (Box) Performance

- mAP@0.5 = 0.8408

- mAP@0.5–0.95 = 0.5539

- Precision (avg) = 0.82

- Recall (avg) = 0.75

- Validation Box Loss = 1.2364

- Validation Class Loss = 0.8686

- Segmentation Loss = 1.8896

Interpretation:

- mAP@0.5 = 0.8408 → indicates high detection accuracy at a moderate IoU threshold.
- mAP@0.5–0.95 = 0.5539 → reflects consistent performance across stricter IoU thresholds.
- Precision ≈ 0.82 / Recall ≈ 0.75 → balanced detection performance with limited false positives and false negatives.
- Validation losses show stable learning with minimal overfitting.

---

Segmentation (Mask) Performance:

- mAP@0.5 = 0.8517
- mAP@0.5–0.95 = 0.5436
- Precision (avg) = 0.85
- Recall (avg) = 0.76
- Validation Mask Loss = 1.8516

Interpretation:

The Mask Precision–Confidence Curve illustrates how precision varies across confidence thresholds for Glioma, Meningioma, and Pituitary tumor classes.
- Meningioma maintained the highest precision overall, consistently staying above 0.85 across most confidence levels.

- Glioma and Pituitary exhibited stable trends, with precision notably improving beyond a 0.5 confidence threshold, reflecting strong confidence calibration.

- The overall precision peaked at 1.00 near a confidence level of 0.86, indicating exceptional reliability when high-confidence predictions are considered.

- These outcomes confirm that YOLOv12’s segmentation head effectively captures and distinguishes tumor boundaries, achieving robust generalization across all three tumor types with balanced precision and recall.

---

Overall Discussion:
The YOLOv12 architecture proved effective for both multi-class detection and segmentation of brain tumors. Its transformer-based backbone enhances spatial feature representation, enabling precise tumor localization and boundary definition.

A slight gap between training and validation losses suggests mild overfitting, which could be mitigated by:
- Increasing augmentation intensity (stronger mosaic or mixup)
- Applying dropout or weight decay
- Expanding the dataset with more MRI variations

Overall, the trained YOLOv12 model provides a robust baseline for automated brain tumor localization and classification. It demonstrates promising generalization, accuracy, and inference efficiency, making it suitable for real-world medical imaging research.

---

### **2.3 Conclusion**
This notebook demonstrates a full workflow for training a YOLOv12-based detector and segmenter for brain tumor localization and classification. It successfully identifies and delineates multiple tumor types with high accuracy and interpretability.

Future Work:
- Expand dataset size
- Perform cross-validation
- Compare with segmentation architectures (e.g., U-Net)
- Integrate explainability modules for clinical interpretability

---

Notes:
- Added real segmentation metrics (from MaskP curve)
- Updated Results and Discussion with Mask Precision-Confidence interpretation
- Balanced discussion between detection and segmentation

# ⚠️ Notice

## This material is the intellectual property of <font color="cyan">Dr. Lysa V. Comia.</font>

## 📌 Notice on Use, Redistribution, and Ethical Compliance  

Redistribution, reproduction, or use of this material beyond personal reference is **strictly prohibited** without the prior written consent of the author. Unauthorized copying, modification, or dissemination—whether for commercial, academic, or institutional purposes—violates intellectual property rights and may result in legal or disciplinary action.  

---

### 🔒 AI Governance and Ethics Considerations  
This work must **not** be used in ways that:  
- ❌ **Compromise data privacy** or violate data protection regulations (e.g., GDPR, Philippine Data Privacy Act).  
- ❌ **Perpetuate bias or discrimination** by misusing algorithms, datasets, or results.  
- ❌ **Enable harmful applications**, including surveillance, profiling, or uses that undermine human rights.  
- ❌ **Misrepresent authorship or credit**, such as plagiarism or omission of proper citations.  

---

### ✅ Responsible Use Principles  
Users are expected to follow responsible research and innovation practices, ensuring that any derivative work is:  
- **Transparent** → Clear acknowledgment of sources and methodology.  
- **Accountable** → Proper attribution and disclosure of limitations.  
- **Beneficial to society** → Applications that align with ethical standards and do not cause harm.  

---

📢 For **any intended use** (academic, research, or practical), prior written approval must be obtained from the author to ensure compliance with both **legal requirements** and **ethical AI practices**.
"""